- name: apt-get update
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

- name: Install essential software
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    # obvious
    - sudo
    # interactive
    - curl
    - htop
    - mosh
    # handy
    - rsync
    - rsyslog
    - bats
    - resolvconf
  # ignore_errors: true

- name: Enable resolvconf
  become: yes
  ansible.builtin.systemd:
    name: resolvconf
    enabled: yes

- name: Start resolvconf
  become: yes
  ansible.builtin.systemd:
    name: resolvconf
    enabled: yes

- name: Add nameservers to server
  become: yes
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/head
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^nameserver 8.8.8.8', line: 'nameserver 1.1.1.1' }
    - { regexp: '^nameserver 1.0.0.1', line: 'nameserver 1.0.0.1' }

- name: Reload nameservers service
  become: yes
  command: "{{ item }}"
  loop:
    - sudo resolvconf --enable-updates
    - sudo resolvconf -u

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Create machinist user
  user:
    name: machinist
    shell: /bin/bash
    groups: wheel
    append: yes
    state: present
    create_home: yes

- name: Create a 2048-bit SSH key for machinist
  ansible.builtin.user:
    name: machinist
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    force: no

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Setup authorized key
  authorized_key:
    user: machinist
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub

- name: Machinist home directory not writable by others
  file:
    path: /home/machinist
    state: directory
    mode: go-w

- name: Machinist .ssh folder 700 permissions
  file:
    path: /home/machinist/.ssh
    state: directory
    owner: machinist
    group: machinist
    mode: 0755

- name: Machinist authorized_keys 644 permissions
  file:
    path: /home/machinist/.ssh/authorized_keys
    state: file
    owner: machinist
    group: machinist
    mode: 0644

- name: Machinist SSH public key 644
  file:
    path: /home/machinist/.ssh/id_rsa.pub
    state: file
    owner: machinist
    group: machinist
    mode: 0644

- name: Machinist SSH private key 600
  file:
    path: /home/machinist/.ssh/id_rsa
    state: file
    owner: machinist
    group: machinist
    mode: 0600

- name: set appropriate hostname
  command: hostname {{ inventory_hostname }}

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: '{{ inventory_hostname }}'
    line: '127.0.0.1 {{ inventory_hostname }}'

- name: Change permission of sshd config
  file:
    path: /etc/ssh/sshd_config
    mode: 0600
  become: yes

- name: Disable root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
    regexp="{{item.re}}"
    line="{{item.line}}"
    state=present
  remote_user: machinist
  become: yes
  with_items:
    - { re: "^PermitRootLogin", line: "PermitRootLogin no" }
    - { re: "^PasswordAuthentication", line: "PasswordAuthentication no" }

- name: Remove authorized keys from root
  file:
    path: /root/.ssh/authorized_keys
    state: absent

- name: Reload sshd
  systemd:
    name: sshd
    state: reloaded
  become: yes
